[build]
  # We want to deploy the 'web' folder
  base = "web"
  
  # The web folder is static, so no build command needed
  command = ""
  
  # Publish the contents of the base directory
  publish = "."

[[redirects]]
  # This handles the /connect redirect for the QR codes
  from = "/connect"
  to = "/index.html"
  status = 200
